FROM tensorflow/tensorflow:latest-py3-jupyter

CMD ["bash", "-c", "source /etc/bash.bashrc && jupyter notebook --NotebookApp.token='mphmph' --notebook-dir=/tf --ip 0.0.0.0 --no-browser --allow-root"]
