version: '3'
services:
 # server:
 #   build: ./server
 #   volumes:
 #       - ./server:/code
 #   ports:
 #       - 5001:80
 #   depends_on:
 #       - redis
  client:
    build: ./client
    ports:
        - 5000:3000
    volumes:
        - .:/app
        - /app/node_modules
   # environment:
    #    - NODE_ENV=development
     #   - CHOKIDAR_USEPOLLING=true
  #redis:
  #  image: "redis:alpine"

