version: '3'
services:
  server:
    build: ./server
    volumes:
        - ./server:/code
    ports:
        - 5001:80
    depends_on:
        - redis
  client:
    build: ./client
    ports:
        - 8080:3000
    volumes:
        - ./client:/app
        - /app/node_modules
    environment:
        - CHOKIDAR_USEPOLLING=true
    depends_on:
        - server
  redis:
    image: "redis:alpine"

