version: '3'
services:
  server:
    build: ./server
    #volumes:
    #    - ./server:/code
    ports:
      - 5001:80
    depends_on:
        - redis
  client:
    build: ./client
    ports:
        - 5000:80
  redis:
    image: "redis:alpine"

